FROM python:3.9

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn requests kafka-python

# Copy your FastAPI code
COPY ./api /app/api

# Expose the app port
EXPOSE 8000

# Start the FastAPI server
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
